---
title: "poster_text"
format: html
---

### Introduction
The Edwards Aquifer is one of the world’s most productive artesian aquifer systems. It provides water for the agricultural, industrial, and domestic needs of over two million people in south central Texas. The limestone aquifer extends nearly 4,000 square miles, of which about 1,250 are exposed at the surface in the recharge zone. South of the recharge zone is the artesian zone, where pressurized water within the confined aquifer can flow upwards in artesian springs. In 2013, the Edwards Aquifer Authority Habitat Conservation Plan (EACHP) issued a 15-year Incidental Take Permit to maintain adequate habitats, flow conditions, and water quality within the San Marcos and Comal Springs. These efforts are tailored to protect 3 endangered species within the aquifer: the Fountain Darter, Comal Springs Riffle Beetle, and Texas Wild Rice. 
The USGS operates over 500 stream gages throughout Texas that allow the EACHP to monitor flow conditions regularly. Each gage measures the water entering the stream system from the groundwater below via springs (springflow) and additional water added to the system from surface-water runoff (streamflow) using the strong mathematical relation between gage height and discharge. In addition to flow conditions, water quality has a considerable impact on the survival of the aquifers’ endangered species. The EAHCP water quality goals include that dissolved oxygen (DO) levels be consistently above 4.0 mg/L, which is a particular concern in wastewater contaminated groundwater. Groundwater tracers are critical to determining the level of wastewater contamination. A particularly well-suited groundwater tracer is sucralose (SUC), an artificial sweetener approved for consumption by the FDA in 1998. The large percentage of SUC not metabolized by the human body is excreted into sewage wastewater, and further resists degradation by normal wastewater treatment processes. Therefore, it is ubiquitously detected in wastewater effluent and environmentally persistent. Additionally, SUC is less prone to false positives and negatives compared to other groundwater tracers. 

###Research Questions
1.	How do sucralose concentrations in San Marcos and Comal springs compare to concentrations reported in other US groundwater systems, surface water bodies, and wastewater treatment plant effluents?
2.	How do the sucralose concentrations at Comal and San Marcos springs compare with each other and what is their relationship to total springflow?

### Methods
Water samples were collected from Hotel Spring in the San Marcos system and Spring Run 3 in the Comal system monthly from January 2021- June 2025.  Sample bottles were submerged directly into flowing springs and not under the influence of surface water runoff. Field duplicates and field blanks were also collected in a similar manner. All sample bottles were kept chilled during transport and frozen until shipment conducted quarterly.  
Sucralose analysis was conducted by commercial laboratory SGS AXYS Analytical Services following their standard procedures MLA-116.  Briefly, aqueous unfiltered samples were spiked with surrogate standard and acidified.  Analysis of the sample extract was performed on an ultra-high performance liquid chromatograph coupled to a triple quadrupole mass spectrometer. Sample blanks did not indicate any issues with lab or field contamination.
Spring discharge data were collected from USGS gaging stations using the R package dataRetrieval (2.7.20).

### Discussion
Sucralose concentrations in the Edwards aquifer springwater are low compared to U.S. averages for wastewater effluent, groundwater and surface waters which suggests minimal wastewater contributions.  Additionally, the Edwards has lower sucralose concentrations than waters with purely recreational influence (with no known wastewater inputs) as documented by Mawhinney et al (2011), further suggesting that the aquifer has minimal anthropogenic contaminant inputs.  
Generally, the San Marcos spring system has greater sucralose concentrations (18.6±14.6ng/L) than the Comal system (10.5±5.5ng/L) indicating a larger amount of wastewater influence in this springshed.  This difference is reduced but still present when a notable outlier (103ng/L) from the San Marcos system is excluded (16.6±6.3). Although sucralose concentrations generally do not vary with springflow (as shown in Figure 2), the variance may be influenced by the Comal systems’ higher average springflow (109 cfs) compared to the San Marcos system (95 cfs). 
Correlations between spring discharge and sucralose concentration at each location were analyzed both with non-detects removed and non-detects set as half the reporting detection limit. San Marcos results indicated a weak positive relationship.  No correlation was present in Comal.  In all cases, the p-values indicated no significant correlation (p-values 0.15-0.81). 

### References

Douglas B. Mawhinney, Robert B. Young, Brett J. Vanderford, Thomas Borch, and Shane A. Snyder Environmental Science & Technology 2011 45 (20), 8716-8722, <https://pubs.acs.org/doi/10.1021/es202404c>

Jibin Li, Xuan Li, Yi Li, Huan Liu, Qilin Wang, Artificial sweeteners in wastewater treatment plants: A systematic review of global occurrence, distribution, removal, and degradation pathways, Journal of Hazardous Materials, Volume 494, 2025, 138644, ISSN 0304-3894, <https://doi.org/10.1016/j.jhazmat.2025.138644.> (<https://www.sciencedirect.com/science/article/pii/S0304389425015602)>

Joan Oppenheimer, Andrew Eaton, Mohammad Badruzzaman, Ali W. Haghani, Joseph G. Jacangelo, Occurrence and suitability of sucralose as an indicator compound of wastewater loading to surface waters in urbanized regions, Water Research, Volume 45, Issue 13, 2011, Pages 4019-4027, ISSN 0043-1354, <https://doi.org/10.1016/j.watres.2011.05.014.> (<https://www.sciencedirect.com/science/article/pii/S0043135411002776)>

Kathryn L. Linge, Yolanta Gruchlik, Francesco Busetti, Una Ryan, Cynthia A. Joll, Use of micropollutant indicator ratios to characterize wastewater treatment plant efficiency and to identify wastewater impact on groundwater, Journal of Environmental Management, Volume 358, 2024, 120822, ISSN 0301-4797, <https://doi.org/10.1016/j.jenvman.2024.120822.> (<https://www.sciencedirect.com/science/article/pii/S0301479724008089)>

Laura A. Richards, Rupa Kumari, Debbie White, Neha Parashar, Arun Kumar, Ashok Ghosh, Sumant Kumar, Biswajit Chakravorty, Chuanhe Lu, Wayne Civil, Dan J. Lapworth, Stefan Krause, David A. Polya, Daren C. Gooddy, Emerging organic contaminants in groundwater under a rapidly developing city (Patna) in northern India dominated by high concentrations of lifestyle chemicals, Environmental Pollution, Volume 268, Part A, 2021, 115765, ISSN 0269-7491, <https://doi.org/10.1016/j.envpol.2020.115765.> (<https://www.sciencedirect.com/science/article/pii/S026974912036454X)>

L.W. Herren, R.A. Brewton, L.E. Wilking, M.E. Tarnowski, M.A. Vogel, B.E. Lapointe, Septic systems drive nutrient enrichment of groundwaters and eutrophication in the urbanized Indian River Lagoon, Florida, Marine Pollution Bulletin, Volume 172, 2021, 112928, ISSN 0025-326X, <https://doi.org/10.1016/j.marpolbul.2021.112928.> (<https://www.sciencedirect.com/science/article/pii/S0025326X21009620)>

W.D. Robertson, D.R. Van Stempvoort, J. Spoelstra, S.J. Brown, S.L. Schiff, Degradation of sucralose in groundwater and implications for age dating contaminated groundwater, Water Research, Volume 88, 2016, Pages 653-660, ISSN 0043-1354, <https://doi.org/10.1016/j.watres.2015.10.051.> (<https://www.sciencedirect.com/science/article/pii/S0043135415303158)>

Yulong Yang, Zhanghua Liu, Huiming Zheng, Shicui Zhu, Kejia Zhang, Xueyan Li, Xiaoyan Ma, Andrea M. Dietrich, Sucralose, a persistent artificial sweetener in the urban water cycle: insights into occurrence, chlorinated byproducts formation, and human exposure, Journal of Environmental Chemical Engineering, Volume 9, Issue 4, 2021, 105293, ISSN 2213-3437, <https://doi.org/10.1016/j.jece.2021.105293.> (<https://www.sciencedirect.com/science/article/pii/S2213343721002700)>
