---
title: "streamflow_analysis"
format: html

execute: 
  echo: false
  warning: false
---
```{r}
#Bringing in data
sms <-readNWISdv(siteNumbers = "08170000", 
                 parameterCd = "00060") 
cs <-readNWISdv(siteNumbers = "08168710", 
                parameterCd = "00060") 
df<-bind_rows(sms,cs)|> renameNWISColumns(df)

gages<- df|> 
  mutate( gage_name = case_when(
    site_no=="08170000"~"San Marcos Springs", 
    site_no=="08168710"~"Comal Springs"), 
    year = year(Date), 
    month = month(Date), 
    day = day(Date))|> 
  rename(cfs = Flow)

gages <- gages|>
  arrange(Date)|>
  mutate(
    avg_30_prior = rollmean(cfs,30,na.pad = TRUE, align = "right"),
    avg_60_prior = rollmean(cfs,60,na.pad = TRUE, align = "right"),
    avg_10_prior = rollmean(cfs,10,na.pad = TRUE, align = "right"))|>
  select(site_no,gage_name,Date,year,month,day,cfs,avg_10_prior,avg_30_prior,avg_60_prior)

(sucralose_raw <- readr::read_csv("C:/Users/mgingerich/OneDrive - Edwards Aquifer Authority/Desktop/Sucralose_Project/data/sucralose_simplified.csv", col_types = cols(
  Date = col_date("%m.%d.%Y"),)))

sucralose <- sucralose_raw|>
  mutate(add_column(sucralose_raw,
    gage_name = case_when(
      str_detect(sys_sample_code, "CM") ~ "Comal Springs",
      str_detect(sys_sample_code, "SM") ~ "San Marcos Springs")))|>
  relocate("gage_name",.before="Date")

sucralose_no_dup <- subset(sucralose,duplicate == "N")
sucralose_no_dup_blank <- subset(sucralose, blank == "N")
false_pos <- sucralose|>
  filter(detect_flag == "Y"& blank == "Y")

stream_sucralose <- sucralose|>
  left_join(gages, join_by(Date,gage_name))|>
  select(Date,gage_name,cfs,avg_10_prior,avg_30_prior,avg_60_prior,result_value,lab_qualifiers,detect_flag)
```

```{r}
#What days have flow higher than 300 cfs?
high_flow_days_300<-tibble(
  filter(gages, cfs>300))
```

```{r}
#What days have no flow/ 0 cfs?
zero_flow_days<-tibble(
  filter(gages, cfs==0))
```

```{r}
#What are the median monthly flows for each gage?
by_gage_month <- gages|>
  group_by(gage_name,month)|>
  summarise(flow_mean = mean(cfs,na.rm=TRUE))|>
  ungroup()
```

```{r}
#What is the average flow per year at each gage?
mean_flow_gage_year <- gages |>
  group_by(gage_name,year)|>
  summarise(mean_flow = mean(cfs,na.rm=TRUE))|>
  ungroup()
```

```{r}
#What day had the highest median flow?
peak_monthday_flows <-gages|>
  group_by(gage_name,month,day)|>
  summarise(median_flow = median(cfs,na.rm=TRUE))|>
  ungroup()|>
  group_by(gage_name)|>
  arrange(desc(median_flow))|>
  slice(1:1)|>
  ungroup()
```

```{r}
spring_stats <- gages|>
  group_by(gage_name)|>
  summarise(mean_cfs = mean(cfs),
            stdv_cfs = sd(cfs),
            min_cfs = min(cfs),
            max_cfs = max(cfs),
            median_cfs = median(cfs))|>
  ungroup()
```