---
title: "sucralose_analysis"
format: html

execute: 
  warning: false
  echo: true
---
```{r}
#loading required packages
library("tidyverse")
library("ggplot2")
library("sf")
library("prismatic")
library("zoo")
library("dataRetrieval")

#Bringing in data
sms <-readNWISdv(siteNumbers = "08170000", 
                 parameterCd = "00060") 
cs <-readNWISdv(siteNumbers = "08168710", 
                parameterCd = "00060") 
df<-bind_rows(sms,cs)|> renameNWISColumns(df)

gages<- df|> 
  mutate( gage_name = case_when(
    site_no=="08170000"~"San Marcos Springs", 
    site_no=="08168710"~"Comal Springs"), 
    year = year(Date), 
    month = month(Date), 
    day = day(Date))|> 
  rename(cfs = Flow)

gages <- gages|>
  arrange(Date)|>
  mutate(
    avg_30_prior = rollmean(cfs,30,na.pad = TRUE, align = "right"),
    avg_60_prior = rollmean(cfs,60,na.pad = TRUE, align = "right"),
    avg_10_prior = rollmean(cfs,10,na.pad = TRUE, align = "right"))|>
  select(site_no,gage_name,Date,year,month,day,cfs,avg_10_prior,avg_30_prior,avg_60_prior)

(sucralose_raw <- readr::read_csv("C:/Users/mgingerich/OneDrive - Edwards Aquifer Authority/Desktop/Sucralose_Project/data/sucralose_simplified.csv", col_types = cols(
  Date = col_date("%m.%d.%Y"),)))

sucralose <- sucralose_raw|>
  mutate(add_column(sucralose_raw,
    gage_name = case_when(
      str_detect(sys_sample_code, "CM") ~ "Comal Springs",
      str_detect(sys_sample_code, "SM") ~ "San Marcos Springs")))|>
  relocate("gage_name",.before="Date")

sucralose_no_dup <- subset(sucralose,duplicate == "N")
sucralose_no_dup_blank <- subset(sucralose, blank == "N")
false_pos <- sucralose|>
  filter(detect_flag == "Y"& blank == "Y")

stream_sucralose <- sucralose|>
  left_join(gages, join_by(Date,gage_name))|>
  select(Date,gage_name,cfs,avg_10_prior,avg_30_prior,avg_60_prior,result_value,lab_qualifiers,detect_flag)
```

```{r}
#How does avg sucralose vary throughout the months at each gage?

sucralose_plot <- sucralose|>
  group_by(gage_name,month)|>
  summarize(sucralose_mean = mean(result_value, na.rm=TRUE))|>
  ungroup()|>
  ggplot(aes(month, sucralose_mean, color=gage_name))+
  geom_point()+
  scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8,9,10,11,12))+
  labs(
    title = "Sucralose by Gage and Month",
    subtitle = "Comal and San Marcos Rivers",
    x = "Month", y = "Average Sucralose (ng/L)")+
  theme(axis.title.x = element_text(margin = margin(t=5)),
        axis.title.y = element_text(margin = margin(r=10)))+
  scale_color_discrete(
    name = "Gage",
    labels = c("Comal River Spring Run 3", "San Marcos Springs Hotel Site"))
sucralose_plot
```

```{r}
#How do average sucralose levels compare between gages?

suc_by_gage <- stream_sucralose|>
  ggplot()+
  geom_boxplot(aes(gage_name,result_value, color = gage_name, 
                   fill = after_scale(clr_desaturate(
                     clr_lighten(color,.8),.8))),linewidth = 0.65)+
  labs(
    title = "Sucralose Levels by Gage",
    x = "Gage",
    y = "Sucralose (ng/L)")+
  theme(legend.position = "none")
```

```{r}
#How does sucralose vary with flow? Does it change when considering average flows from the previous weeks/month?

plot1 <- stream_sucralose|>
ggplot()+
  geom_point(aes(avg_30_prior,result_value, color = gage_name,shape=gage_name), na.rm = TRUE)+
  theme(legend.position = "none",)+
  labs(
    x = "30-day Prior Avg Flow (cfs)",
    y = "Sucralose (ng/L)")

plot2 <- stream_sucralose|>
  ggplot()+
  geom_point(aes(avg_10_prior, result_value, color = gage_name,shape = gage_name),na.rm = TRUE)+
  theme(legend.position = "none")+
  labs(
  title = "Sucralose Levels by Flow",
    subtitle = "Comal and San Marcos Springs",
  x = "10-day Prior Avg Flow (cfs)",
  y = "Sucralose (ng/L)")

plot3 <- stream_sucralose|>
  ggplot()+
  geom_point(aes(avg_60_prior, result_value, color = gage_name,shape=gage_name), na.rm = TRUE)+
  theme(legend.position = "bottom",
        legend.margin = margin(l=220),
        legend.title = element_blank())+
  labs(
    x = "60-day Prior Avg Flow (cfs)",
    y = "Sucralose (ng/L)")

plot4 <- stream_sucralose|>
  ggplot()+
  geom_point(aes(cfs,result_value,color=gage_name,shape=gage_name),na.rm=TRUE)+
  theme(legend.position = "none")+
  labs(
    x = "Day-of Flow (cfs)",
    y = "Sucralose (ng/L)")

```

```{r}
#Calculating SUC load in g/day for each gage and day

load <- stream_sucralose|>
  mutate(
    load = cfs*result_value*0.0024468)

load|>
  ggplot()+
  geom_point(aes(Date,load, color = gage_name))
```

```{r}
#table summary information for sucralose data
detect_stats <- sucralose|>
  group_by(gage_name)|>
  filter(detect_flag == "Y",
         result_value < 100)|>
  summarise(mean_suc = mean(result_value),
            min_suc = min(result_value),
            max_suc = max(result_value),
            median_suc = median(result_value),
            mean_detect = mean(reporting_detection_limit),
            num_detect = n(),
            st_dev = sd(result_value))|>
  ungroup()

suc_summary_stats <- sucralose|>
  group_by(gage_name)|>
  summarise(n_tot = n())|>
  ungroup()|>
left_join(sum_stat, join_by(gage_name))|>
  mutate(
    perc_detect = num_detect/n_tot*100,
    perc_non = 100-perc_detect)
```

```{r}
#Analyzing the correlation between springflow and sucralose with non detects set as half the RDL

ndhalf_stream_sucralose<-stream_sucralose|>
  filter(gage_name == "Comal Springs")|>
  mutate(half_ND = case_when(
    detect_flag == "N" ~ result_value/2,
    detect_flag == "Y" ~ result_value/1))

result <- cor.test(ndhalf_stream_sucralose$cfs,ndhalf_stream_sucralose$half_ND, use = "pairwise.complete.obs")
#Extract values
r <- result$estimate
t <- result$statistic
p <- result$p.value

#Print
r
t
p
```

```{r}
#Analyzing the correlation between springflow and sucralose with non detects removed

rm_stream_sucralose<-stream_sucralose|>
  filter(gage_name == "San Marcos Springs",
         detect_flag == "Y")

result <- cor.test(rm_stream_sucralose$cfs,rm_stream_sucralose$result_value, use = "pairwise.complete.obs")
#Extract values
r <- result$estimate
t <- result$statistic
p <- result$p.value

#Print
r
t
p
```